# Generated by Django 6.0.4 on 2026-04-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
