# Generated by Django 6.0.4 on 2026-04-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_profile_rejection_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="citizenship_no",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="fullname",
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="issued_district",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="permanent_address",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
