# Generated by Django 6.0.4 on 2026-04-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_profile_citizenship_no_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="speciality",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
