# Generated by Django 6.0.4 on 2026-04-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_profile_speciality"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_photos"),
        ),
    ]
