# Generated by Django 6.0.4 on 2026-04-16 15:43

import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_profile_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="citizenship_back",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="citizenships",
                validators=[main.validators.validate_file_size],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="citizenship_front",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="citizenships",
                validators=[main.validators.validate_file_size],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_photos",
                validators=[main.validators.validate_file_size],
            ),
        ),
    ]
