# Generated by Django 6.0.4 on 2026-04-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_myuser_is_staff"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="groups",
            field=models.ManyToManyField(to="auth.group"),
        ),
    ]
