# Generated by Django 6.0.4 on 2026-04-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_myuser_is_superuser_myuser_user_permissions"),
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="currency",
            field=models.CharField(
                choices=[("npr", "रु"), ("inr", "₹"), ("usd", "$")], default="npr"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="per_day_fee",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="myuser",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
    ]
