# Generated by Django 6.0.4 on 2026-04-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_profile_currency_profile_per_day_fee_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Speciality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="profile",
            name="speciality",
        ),
        migrations.AddField(
            model_name="profile",
            name="specialities",
            field=models.ManyToManyField(
                related_name="profiles", to="accounts.speciality"
            ),
        ),
    ]
