# Generated by Django 6.0.4 on 2026-04-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_speciality_remove_profile_speciality_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="speciality",
            options={"verbose_name_plural": "Specialities"},
        ),
        migrations.AddField(
            model_name="speciality",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
