# Generated by Django 6.0.4 on 2026-05-05 15:14

import main.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_emailverifyotp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="citizenship_back",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="citizenships",
                validators=[main.validators.validate_file_size],
                verbose_name="Citizenship Back",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="citizenship_front",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="citizenships",
                validators=[main.validators.validate_file_size],
                verbose_name="Citizenship Front",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="citizenship_no",
            field=models.CharField(
                max_length=20, null=True, verbose_name="Citizenship No"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="currency",
            field=models.CharField(
                choices=[("npr", "रु"), ("inr", "₹"), ("usd", "$")],
                default="npr",
                verbose_name="Currency",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="date_of_birth",
            field=models.DateField(null=True, verbose_name="Date of birth"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="email_verified",
            field=models.CharField(
                choices=[("pending", "Pending"), ("verified", "Verified")],
                default="pending",
                verbose_name="Email Verification Status",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="fullname",
            field=models.CharField(max_length=60, null=True, verbose_name="Full Name"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="issued_district",
            field=models.CharField(
                max_length=30, null=True, verbose_name="Issued District"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="kyc_verified",
            field=models.CharField(
                choices=[
                    ("not_submitted", "Not Submitted"),
                    ("in_review", "In Review"),
                    ("rejected", "Rejected"),
                    ("verified", "Verified"),
                ],
                default="not_submitted",
                verbose_name="KYC Verification Status",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="per_day_fee",
            field=models.PositiveIntegerField(default=0, verbose_name="Per day fee"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="permanent_address",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Permanent Address"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="profile_photos",
                validators=[main.validators.validate_file_size],
                verbose_name="Profile Photo",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="rejection_reason",
            field=models.TextField(
                blank=True, null=True, verbose_name="Rejection Reason"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="specialities",
            field=models.ManyToManyField(
                related_name="profiles",
                to="accounts.speciality",
                verbose_name="Specialities",
            ),
        ),
    ]
