# Generated by Django 6.0.4 on 2026-04-20 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0013_alter_speciality_options_speciality_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "duration",
                    models.CharField(
                        default=1, help_text="Enter duration in days. Eg. 5"
                    ),
                ),
                (
                    "no_of_cameras",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="No of cameras included in the package",
                        null=True,
                    ),
                ),
                (
                    "no_of_staffs",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="No of staffs required for the package",
                        null=True,
                    ),
                ),
                ("drone_included", models.BooleanField(default=False)),
                (
                    "free_accessories",
                    models.TextField(
                        blank=True,
                        help_text="Eg. Free 32GB pendrive, Free medium size photo album etc.",
                        null=True,
                    ),
                ),
                (
                    "delivery_time",
                    models.PositiveIntegerField(
                        help_text="Enter duration in days when final results will be delivered. Eg. 5 days"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, help_text="Price of package", max_digits=10
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2, help_text="Discount amount", max_digits=10
                    ),
                ),
                (
                    "discount_text",
                    models.CharField(
                        blank=True,
                        help_text="Eg. Wedding season",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "discount_end_date",
                    models.DateField(help_text="Its offer ending date"),
                ),
                (
                    "photographer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="accounts.profile",
                    ),
                ),
            ],
            options={
                "unique_together": {("photographer", "name")},
            },
        ),
    ]
