# Generated by Django 6.0.4 on 2026-05-05 15:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "value",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="API key for third party integration",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("customer_name", models.CharField(max_length=100)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateField(auto_now_add=True)),
                ("expires_at", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
