# Generated by Django 6.0.4 on 2026-05-05 15:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_apikey"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="value",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="API key for third party integration",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
