# Generated by Django 6.0.4 on 2026-05-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_apikey_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apikey",
            name="expires_at",
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
