# Generated by Django 6.0.4 on 2026-04-30 15:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSubscriptionBooking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("s_type", models.CharField(max_length=50)),
                ("s_valid_no_of_days", models.PositiveIntegerField(null=True)),
                (
                    "s_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("s_currency", models.CharField(default="npr")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("terminated", "Terminated"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                    ),
                ),
                ("khalti_status", models.CharField(max_length=50)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="subscriptions.subscription",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subs_booking",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
