# Generated by Django 6.0.4 on 2026-05-01 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_usersubscriptionbooking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="currency",
            field=models.CharField(
                choices=[("npr", "रु"), ("inr", "₹"), ("usd", "$")], default="npr"
            ),
        ),
        migrations.AlterField(
            model_name="usersubscriptionbooking",
            name="khalti_status",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
