# Generated by Django 6.0.4 on 2026-05-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_alter_subscription_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscriptionbooking",
            name="pidx",
            field=models.CharField(
                help_text="Initial payment request id from khalti",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="usersubscriptionbooking",
            name="khalti_status",
            field=models.CharField(
                help_text="Exact status from khalti", max_length=50, null=True
            ),
        ),
    ]
