# Generated by Django 6.0.4 on 2026-04-22 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Enter email to verify yourself as interested customer",
                        max_length=254,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Eg. 98********, phone number for verbal communication with photograher",
                        max_length=10,
                    ),
                ),
                (
                    "fullname",
                    models.CharField(
                        help_text="Your fullname matching citizenship name",
                        max_length=60,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("delivered", "Delivered"),
                        ],
                        default="requested",
                    ),
                ),
                ("final_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("name", models.CharField(max_length=100)),
                (
                    "duration",
                    models.CharField(
                        default=1, help_text="Enter duration in days. Eg. 5"
                    ),
                ),
                (
                    "no_of_cameras",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="No of cameras included in the package",
                        null=True,
                    ),
                ),
                (
                    "no_of_staffs",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="No of staffs required for the package",
                        null=True,
                    ),
                ),
                ("drone_included", models.BooleanField(default=False)),
                (
                    "free_accessories",
                    models.TextField(
                        blank=True,
                        help_text="Eg. Free 32GB pendrive, Free medium size photo album etc.",
                        null=True,
                    ),
                ),
                (
                    "delivery_time",
                    models.PositiveIntegerField(
                        help_text="Enter duration in days when final results will be delivered. Eg. 5 days"
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="main.package",
                    ),
                ),
            ],
        ),
    ]
