# Generated by Django 6.0.4 on 2026-04-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="author",
            field=models.CharField(
                blank=True,
                choices=[("photographer", "Photographer"), ("customer", "Customer")],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
