# Generated by Django 6.0.4 on 2026-04-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0002_booking_author_booking_created_at_booking_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="start_date",
            field=models.DateField(help_text="Booking date", null=True),
        ),
    ]
