# Generated by Django 6.0.4 on 2026-04-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_booking_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="end_date",
            field=models.DateField(editable=False, null=True),
        ),
    ]
