# Generated by Django 6.0.4 on 2026-04-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_booking_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
